version: '3'
services:
  fastapi:
    build:
      context: src
      dockerfile: src/Dockerfile
    env_file:
      - fastapi.env
    volumes:
      - ./src/alembic/versions:/app/alembic/versions
    depends_on:
      - database
      - redis

  redis:
    image: docker.io/bitnami/redis:7.2.1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"

  database:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
    ports:
      - "80:80"

volumes:
  pgdata: